ubicaciones = {
"type": "FeatureCollection",
"name": "ubicaciones",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": 2, "nombre": "", "direccion": " ", "horario_atencion": "", "contacto": "", "comunicacion": "", "atencion_brindada": "", "informacion_relevante": "" }, "geometry": "" },
{ "type": "Feature", "properties": { "id": 1, "nombre": "DIRECCIÓN GENERAL DE LA MUJER JOSÉ C. PAZ", "direccion": "Hipolito Yrigoyen 2945, José C. Paz", "horario_atencion": "Lunes a viernes de 08:00hs a 14:00 hs", "contacto": "1156681016 wsp", "comunicacion": "", "atencion_brindada": "Ofrecen distintas herramientas como botón antipánico, dispositivo dual y Programa Acompañar.", "informacion_relevante": "Su objetivo es no naturalizar los actos de violencia brindando ayuda a las mujeres para que logren tener autonomía." }, "geometry": { "type": "Point", "coordinates": [ -58.764148903275327, -34.524832379602977 ] } },
{ "type": "Feature", "properties": { "id": 3, "nombre": "COMISARÍA DE LA MUJER JOSÉ C. PAZ", "direccion": "Av. Croacia 1742, Jose C. Paz", "horario_atencion": "24hs", "contacto": "144 línea telefónica gratuita", "comunicacion": "dgm4565ccmjcp@hotmail.com", "atencion_brindada": "Abordan casos de violencia de género y maltrato infantil, en la línea telefónica brindan atención, herramientas y conocimientos sobre violencia de género.", "informacion_relevante": "Cuentan con el programa Acompañar que está dirigido a mujeres y el colectivo LGBTI+ que pasan situaciones de violencia de género." }, "geometry": { "type": "Point", "coordinates": [ -58.792292103738738, -34.517221943887762 ] } },
{ "type": "Feature", "properties": { "id": 4, "nombre": "DIRECCIÓN DE PROTECCIÓN INTEGRAL A LA VÍCTIMA JOSÉ C. PAZ", "direccion": "Hipolito Irigoyen 3002", "horario_atencion": "Lunes a viernes de 8 a 14 hs", "contacto": "02320-440511", "comunicacion": "dppiv2023@gmail.com", "atencion_brindada": "Trabajan en las escuelas dando información a los  adolescentes, también promocionando los derechos.", "informacion_relevante": "Diferentes grupos de víctimas ,funcionarios municipales, colegios de abogados ,donde se realiza  taller de contención para las mujeres." }, "geometry": { "type": "Point", "coordinates": [ -58.764526697527153, -34.525031969019032 ] } },
{ "type": "Feature", "properties": { "id": 5, "nombre": "LA CASITA TE ACOMPAÑA JOSÉ C. PAZ", "direccion": "Compostella 1973 Barrio Alberdi José C. Paz\n", "horario_atencion": "Todos los días", "contacto": "", "comunicacion": "", "atencion_brindada": "Ayuda a crear una red de comprentención  para familias víctimas de violencia.", "informacion_relevante": "Cuentan con talleres, apoyo escolar , profesionales tales como psicólogos, abogados, asistentes sociales, etc." }, "geometry": { "type": "Point", "coordinates": [ -58.763302385829761, -34.50112658742394 ] } },
{ "type": "Feature", "properties": { "id": 6, "nombre": "CENTRO COMUNITARIO SANTA MARIA DE LOS ÁNGELES JOSÉ C. PAZ", "direccion": "Blasco Ibañez 3918, Jose C. Paz", "horario_atencion": "8 a 12 hs y 13 a 16 hs", "contacto": "112404-9692 wsp", "comunicacion": "Santa Maria de los Angeles (Facebook)", "atencion_brindada": "Apoyo escolar, ayuda alimentaria, acompañamiento para las infancias haciendo respetar sus derechos, talleres e informan sobre la ESI.", "informacion_relevante": "Trabajan en conjunto con las familias,\n escuelas de la zona y otros centros de red encuentro." }, "geometry": { "type": "Point", "coordinates": [ -58.750137018688285, -34.538268578460276 ] } },
{ "type": "Feature", "properties": { "id": 7, "nombre": "ORVIG UNPAZ JOSÉ C. PAZ", "direccion": "Leonardo N. Alem 4731", "horario_atencion": "Lunes a viernes entre las 10 am a 17pm hs", "contacto": "1128455962", "comunicacion": "orvig@unpaz.edu.ar", "atencion_brindada": "Asesoramiento y acompañamiento de víctimas de violencia de género y discriminación.", "informacion_relevante": "Asisten solo a estudiantes o personal de la UNPAZ, no es abierto a la comunidad." }, "geometry": { "type": "Point", "coordinates": [ -58.745611980999357, -34.520885455679192 ] } },
{ "type": "Feature", "properties": { "id": 8, "nombre": "CENTRO COMUNITARIO NUESTRO FUTURO JOSÉ C. PAZ", "direccion": "Dinamarca 3735, en el barrio Sol y Verde", "horario_atencion": "Horario de atención: 8 a 17 hs.", "contacto": "02320-622515", "comunicacion": "nuestro_futurosyv@hotmail.com", "atencion_brindada": "Problemáticas socioeconómicas que afectan a todos los vecinos, guardería comunitaria. Cuentan con talleres, el aprendizaje se da a través del juego y el arte.", "informacion_relevante": "A pesar de no contar con profesionales para abordar  la violencia de género, armaron su propia red de contención articulándose  junto a diferentes instituciones para poder acompañar en este tipo de situaciones." }, "geometry": { "type": "Point", "coordinates": [ -58.798968694426222, -34.501998071535908 ] } },
{ "type": "Feature", "properties": { "id": 9, "nombre": "CENTRO COMUNITARIO LAGARTO JUANCHO \nJOSÉ. C. PAZ", "direccion": "Colonia 4730", "horario_atencion": "8:00hs  a 17:00 hs", "contacto": "Instagram   c.c.lagarto_juancho\n", "comunicacion": "centro.comunitario.lj16@gmail.com", "atencion_brindada": "Espacio de contención y cuidado a niños y niñas que pasaron por violencia y abuso.", "informacion_relevante": "Integrar y trabajar con las familias con diferentes problemáticas que están trascendiendo.  Hay actividades para los chicos, como taller de música, arte, percursión." }, "geometry": { "type": "Point", "coordinates": [ -58.802859288113574, -34.514253050243305 ] } },
{ "type": "Feature", "properties": { "id": 10, "nombre": "DINAF JOSÉ C. PAZ", "direccion": "Zuviría 4800, José. C. Paz", "horario_atencion": "8 a 17 hs", "contacto": "01124867854", "comunicacion": "", "atencion_brindada": "Este sistema de proteccion y promocion de derechos de las infancias, interviniendo activamente y directamente (sin pasar por un juzgado antes) los casos de vulneración de derechos, violencia.", "informacion_relevante": "El equipo profesional brinda un acompañamiento mas especifico, coordinado y articulado para la comunidad,  la vulneración y violencia en la niñez y adolescencia." }, "geometry": { "type": "Point", "coordinates": [ -58.748673524007245, -34.522325347180896 ] } },
{ "type": "Feature", "properties": { "id": 11, "nombre": "COMISARIA DE LA MUJER SAN MIGUEL", "direccion": "El Zonda 2484", "horario_atencion": "24hs", "contacto": "1144550371", "comunicacion": "comisariadelamujersanmiguel@yahoo.com.ar", "atencion_brindada": "Atención a personas víctimas de violencia de género, brindando un tratamiento integral e interdisciplinario por medio del servicio legal, psicológico y social.", "informacion_relevante": "Se realiza toma de la denuncia y contener a la víctima a través de una trabajadora social y un abogado . En algunos casos va un patrullero preventivo." }, "geometry": { "type": "Point", "coordinates": [ -58.748260711076668, -34.561436895472802 ] } },
{ "type": "Feature", "properties": { "id": 12, "nombre": "COOPERATIVA FRIDA KALHO SAN MIGUEL", "direccion": "Tribulato 1082, esquina Paunero, San Miguel", "horario_atencion": "Lunes, martes, jueves y viernes de 09:00 a 20:00hs, miércoles de 09:00 a 20:30hs", "contacto": "0113906-0766", "comunicacion": "espaciodegenerointegral@gmail.com", "atencion_brindada": "Grupos de ayuda mutua, primera escucha y contención, asesoría legal, consejería ILE, etc.", "informacion_relevante": "Realizan actividades en los barrios con el fin de detectar la violencia y las problemáticas territoriales." }, "geometry": { "type": "Point", "coordinates": [ -58.71272137067713, -34.540188588311608 ] } },
{ "type": "Feature", "properties": { "id": 13, "nombre": "UNGS OFICINA DE POLÍTICAS DE GÉNERO", "direccion": "Julio A Roca 812. San Miguel", "horario_atencion": "10 a 19 hs", "contacto": "4469-7500. Interno (7185)", "comunicacion": "políticasdegénero@ungs.edu.ar", "atencion_brindada": "Institución de educación superior, cuya misión es la construcción, formación, investigación y promoción del desarrollo social en todos sus ámbitos. Interviniendo activamente en la realización de la comunidad universitaria democrática.", "informacion_relevante": "Posee un gran proyecto, el cual ofrece actividades (info y herramientas) sobre géneros y diversidad, dando a conocer una visión más compleja sobre estos enfoques." }, "geometry": { "type": "Point", "coordinates": [ -58.712827050787347, -34.536256407543831 ] } },
{ "type": "Feature", "properties": { "id": 14, "nombre": "COMISARÍA DE LA MUJER GRAN BOURG", "direccion": "Avenida Sesquicentenario 158 Gan Bourg, Malvinas Argentinas.", "horario_atencion": "24 horas", "contacto": "02320-423193", "comunicacion": "", "atencion_brindada": "", "informacion_relevante": "" }, "geometry": { "type": "Point", "coordinates": [ -58.7275099811011, -34.508814805589928 ] } },
{ "type": "Feature", "properties": { "id": 15, "nombre": "SECRETARÍA DE LA MUJER MORENO", "direccion": "Hipólito Yrigoyen 70 Moreno Centro", "horario_atencion": "Lunes a Viernes de 08:00 a 16:00 horas.", "contacto": "0237 2646140 o 1164121474(solo WhatsApp)", "comunicacion": "www.moreno.gob.ar", "atencion_brindada": "Se encarga de brindar atención, asesoramiento y contención a personas en situaciones de violencia por motivos de género.", "informacion_relevante": "Cuentan con talleres especializados en ESI, masculinidades, programa acompañar y puntos violeta donde tienen promotoras de género capacitadas en la ley Micaela García." }, "geometry": { "type": "Point", "coordinates": [ -58.794630061104861, -34.650111314623622 ] } },
{ "type": "Feature", "properties": { "id": 16, "nombre": "SUBSECRETARÍA DE LA MUJER, NIÑEZ, Y ADOLESCENCIA MALVINAS", "direccion": "Palacio municipal , ex av. Perón N°4276", "horario_atencion": "8:00 a 18:00hs de lunes a viernes, y  sábados de 8:00 a 13:00hs ,líneas activas las 24 horas.", "contacto": "(011-4660-9000) y el email institucional ssmujer@malvinas.gob.ar", "comunicacion": "144 que es el número de referencia a nivel nacional", "atencion_brindada": "Violencia de género y brindar apoyo a las mujeres, niños y adolescentes que lo necesiten.", "informacion_relevante": "Se realizan charlas,tienen un grupo de taller de costura para mujeres,también utilizan el programa ACOMPAÑAR." }, "geometry": { "type": "Point", "coordinates": [ -58.700797131573914, -34.496951112383208 ] } },
{ "type": "Feature", "properties": { "id": 17, "nombre": "CENTRO COMUNITARIO CAMPANITA DEL VISO", "direccion": "Azcuénaga 2890. Del Viso", "horario_atencion": "8 a 17 hs.", "contacto": "", "comunicacion": "Claudia Galvan.", "atencion_brindada": "De los niños y familias, ya sea en salud, desarrollo social y educativo.", "informacion_relevante": "En un principio funcionaba como espacio de cuidados de  primera infancia pero se vio obligado a transformarse en una  inst (que garantice los derechos y la educación) ante las necesidades de los niños que asistían. Ya que en los jardines de la zona no habían vacantes y esos niños quedaban excluidos." }, "geometry": { "type": "Point", "coordinates": [ -58.793578704539847, -34.443674636253967 ] } }
]
}
